### ISSUE TITLE
Update travis and cloudbees

### ISSUE THREAD

**Issue by jbaris** [fluxitsoft/jqa#10]
Currently, works on jbaris account (see README.markdown)

**Comment by surrizola** [comment]
Done travis change
https://travis-ci.org/fluxitsoft/jqa

**Comment by jbaris** [comment]
Great!
Lets remove the cloudbees integration (its reduntant) at te README.markdown page. Agree?
Before close this issue, lets test if the pull request activates the build in Travis (see http://about.travis-ci.org/blog/announcing-pull-request-support/)

**Comment by surrizola** [comment]
Totally agree !!
i just tested without pull request and it works ok. 
For example https://travis-ci.org/fluxitsoft/jqa/builds/9519480

Just make a push to the master and travil will build on the fly.

If you can check this with another push and see if travis builds automatically we can close this issue

**Comment by jbaris** [comment]
It's work like a charm. See:
https://github.com/fluxitsoft/jqa/pull/15
and
https://travis-ci.org/fluxitsoft/jqa/pull_requests
I will close this issue.
