### ISSUE TITLE
Add Maven 3 support

### ISSUE THREAD

**Issue by jbaris** [fluxitsoft/jqa#2]
Currently, only works with Maven 2.

**Comment by surrizola** [comment]
i just run the test with maven 3 and it works.  My version is 3.0.4
mvn ar.com.fluxit.jqa:jqa-maven-plugin:check at jqa-test-parent
The result xml file is created ok (results-jqa-test-project.xml) but the xm is empty

**Comment by jbaris** [comment]
If you run this test with Maven 2.2.1, the file results-jqa-test-project.xml have entries.

I as remember, the problem is in JQAMavenPlugin, at: 
https://github.com/fluxitsoft/jqa/blob/7dee5dec03940a48bcc7af2fcfb6e2099a4b048c/jqa-parent/jqa-maven-plugin/src/main/java/ar/com/fluxit/jqa/JQAMavenPlugin.java#L137

```
final Set<Artifact> artifacts = project.getArtifacts();
```

See http://mail-archives.apache.org/mod_mbox/maven-users/201101.mbox/%3C1294669059735-3334878.post@n5.nabble.com%3E

**Comment by surrizola** [comment]
if i run with maven 3.0.4 the file  results-jqa-test-project.xml have entries have entries to, do you think the problem is the plugin ? or some type of configuration ?
Example of the xml result file
<ar.com.fluxit.jqa.result.CheckingResult>
  <date>2013-07-26 15:12:24.127 ART</date>
  <ruleChecksFailed>
    <ar.com.fluxit.jqa.result.RuleCheckFailed>
      <ruleName>Entity naming</ruleName>
      <ruleMessage>The Entity &apos;ar.com.fluxit.jqa.test.entities.vehicles.Car&apos; must be named like &apos;**.entity.**&apos;</ruleMessage>
      <targetClassName>ar.com.fluxit.jqa.test.entities.vehicles.Car</targetClassName>

**Comment by jbaris** [comment]
Also tested on Maven 3.2.1.
