### ISSUE TITLE
Chage the keyword "Contract" to "API"

### ISSUE THREAD

**Issue by jbaris** [fluxitsoft/jqa#4]
In english it's most common to use "API" rather than "Contract". Replace all occurences.

**Comment by surrizola** [comment]
this keyword is present in the source code or inside the documentations pages ?

**Comment by jbaris** [comment]
Both. In the source code (mostly in rules names/descriptions) and also in the README.markdown (the user manual is available only in spanish yet).

**Comment by surrizola** [comment]
i recently commit somes changes in the ruleset definition of the test-project, do you think is necesary to change the keyword in anothers places besides de Readme ?

**Comment by jbaris** [comment]
Great!
That's enough. Pull the changes and close this issue.
